apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{  .Chart.Name }}-zipkin-deployment"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.zipkinReplicaCount }}
  template:
    metadata:
      labels:
        app: "{{  .Chart.Name }}-selector"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:{{ .Values.zipkinImageVersion }}
        env:
          - name: STORAGE_TYPE
            value: "cassandra"
          - name: STORAGE_PORT_9042_TCP_ADDR
            value: "cassandra"
          - name: JAVA_OPTS
            value: "-Dlogging.level.zipkin=ERROR -Dlogging.level.zipkin2=ERROR -Dnetworkaddress.cache.ttl=15"
        ports:
        - containerPort: 9411
          name: zipkin-api
        readinessProbe:
          httpGet:
            path: "/api/v1/services"
            port: 9411
          initialDelaySeconds: 5
