apiVersion: v1
kind: Service
metadata:
  name: "{{  .Chart.Name }}-zipkin-service"
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ default "ClusterIP" .Values.service.type | quote }}
  selector:
    app: "{{  .Chart.Name }}-selector"
  ports:
  - name: webui
    port: 80
    targetPort: 9411
  - name: api
    port: 9411
    targetPort: 9411